FROM eclipse-temurin:21-jdk-jammy

RUN apt-get update && apt-get install -y --no-install-recommends \
    fakeroot dpkg-dev binutils \
    libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev \
    libfreetype6 fontconfig \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project
COPY . .
RUN chmod +x gradlew

RUN ./gradlew packageDeb --no-daemon

CMD ["cp", "-r", "build/compose/binaries/main/deb/.", "/output"]
